using UnityEngine;

public class PlayerMovement : MonoBehaviour
{
    public float moveSpeed = 5f;

    public Rigidbody2D rb;
    
    public Animator animator;

    public Collider2D[] colliders = new Collider2D[3];

    Vector2 movement;


    void Update()
    {
        ///Update player input

        InputUpdate();

       
    }

    void FixedUpdate()
    {
        /// Movement
        
        rb.MovePosition(rb.position + movement * moveSpeed * Time.fixedDeltaTime);
    }

    void InputUpdate()
    {
        ///Player input
        ///Animation

        movement.x = Input.GetAxisRaw("Horizontal");
        movement.y = Input.GetAxisRaw("Vertical");
        movement.Normalize();

        animator.SetFloat("Horizontal", movement.x);
        animator.SetFloat("Vertical", movement.y);
        animator.SetFloat("Speed", movement.sqrMagnitude);
    }

   

   

  
}
